version: '3.9'

services:
  app:
    build: ./team_finder
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  parser:
    build: ./parser_app
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_finder
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge